name: Update Changelog

# Trigger on every push to main/master branch
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog from Commits
        run: |
          echo "# Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "All commits in chronological order (newest first):" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          
          # Get all commits with date, author, and message
          git log --pretty=format:"## %ad - %an%n- **%s**%n" --date=short >> CHANGELOG.md

      - name: Commit Updated Changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: update changelog [skip ci]"
            git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
