name: Update Changelog

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog from Commits
        run: |
          echo "# Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "All notable changes to this project are documented in this file." >> CHANGELOG.md
          echo "" >> CHANGELOG.md

          git log \
            --pretty=format:"%ad|||%an|||%s" \
            --date=short \
            --grep="docs: update changelog" \
            --grep="update changelog.yml" \
            --grep="create changelog.yml" \
            --grep="\[skip ci\]" \
            --invert-grep |
          sort -r |
          awk -F'|||' '
            {
              if ($1 != current_date) {
                current_date = $1;
                print "";
                print "## " current_date;
              }
              print "- " $3 " _(by " $2 ")_";
            }
          ' >> CHANGELOG.md

      - name: Commit Updated Changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: update changelog [skip ci]"
            git push
          fi
