name: Update Changelog
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Changelog from Commits
        run: |
          cat > CHANGELOG.md << 'EOL'
          # Changelog
          All commits in chronological order (newest first):
          EOL
          git log --pretty=format:"## %ad - %an%n- **%s**%n%b%n" --date=short --grep="docs: update changelog" --grep="Update changelog.yml" --grep="Create changelog.yml" --grep="\[skip ci\]" --invert-grep >> CHANGELOG.md
      - name: Commit Updated Changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: update changelog [skip ci]"
            git push
          fi
