name: Update Changelog

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Full Keep a Changelog Format
        run: |
          python3 << 'EOF'
          import subprocess
          import re
          import sys
          from datetime import datetime
          from collections import defaultdict

          def get_filtered_commits():
              """Get commits excluding workflow update noise"""
              cmd = [
                  'git', 'log', '--pretty=format:%s|||%b|||%an|||%ad|||%H|||%D',
                  '--date=short',
                  '--grep=docs: update changelog',
                  '--grep=Update changelog.yml',
                  '--grep=Create changelog.yml',
                  '--grep=\\[skip ci\\]',
                  '--invert-grep'
              ]
              try:
                  result = subprocess.run(cmd, capture_output=True, text=True, check=True)
                  return result.stdout.strip().split('\n') if result.stdout.strip() else []
              except subprocess.CalledProcessError as e:
                  print(f"Error getting commits: {e}")
                  return []

          def get_tags():
              """Get all git tags with dates"""
              try:
                  cmd = ['git', 'tag', '--sort=-creatordate', '--format=%(refname:short)|||%(creatordate:short)']
                  result = subprocess.run(cmd, capture_output=True, text=True, check=True)
                  tags = []
                  for line in result.stdout.strip().split('\n'):
                      if line.strip():
                          parts = line.split('|||')
                          if len(parts) >= 2:
                              tags.append({'name': parts[0], 'date': parts[1]})
                  return tags
              except subprocess.CalledProcessError:
                  return []

          def categorize_commit(subject, body):
              """Categorize based on keywords in subject/body"""
              text = (subject + ' ' + body).lower()

              if any(word in text for word in ['security', 'vulnerability', 'cve', 'exploit']):
                  return 'security'
              if any(phrase in text for phrase in ['breaking change', 'breaking:', 'break:']):
                  return 'breaking'
              if any(word in text for word in ['deprecat', 'obsolete', 'phase out']):
                  return 'deprecated'
              if any(word in text for word in ['remove', 'delete', 'drop', 'eliminate']):
                  return 'removed'
              if any(word in text for word in ['fix', 'resolve', 'correct', 'patch', 'bug', 'issue']):
                  return 'fixed'
              if any(word in text for word in ['add', 'new', 'create', 'implement', 'feat', 'feature']):
                  return 'added'
              return 'changed'

          def format_commit_entry(commit):
              """Format a commit with optional body lines"""
              entry = f"- **{commit['subject']}** ({commit['date']} - {commit['author']})"
              if commit['body']:
                  body_lines = [line.strip() for line in commit['body'].split('\n') if line.strip()]
                  if body_lines:
                      entry += "\n"
                      for line in body_lines:
                          entry += f"  {line}\n"
              return entry

          def generate_full_changelog():
              commits = get_filtered_commits()
              tags = get_tags()
              categorized = defaultdict(list)

              for line in commits:
                  if not line.strip():
                      continue
                  parts = line.split('|||')
                  if len(parts) >= 6:
                      subject, body, author, date, hash_id, refs = map(str.strip, parts[:6])
                      category = categorize_commit(subject, body)
                      
                      # Check if this commit has a tag
                      tag_name = None
                      if refs and 'tag:' in refs:
                          # Extract tag name from refs
                          for ref in refs.split(','):
                              if 'tag:' in ref:
                                  tag_name = ref.split('tag:')[1].strip()
                                  break
                      
                      categorized[category].append({
                          'subject': subject,
                          'body': body,
                          'author': author,
                          'date': date,
                          'hash': hash_id[:7],
                          'tag': tag_name
                      })

              changelog_lines = [
                  "# Changelog",
                  "",
                  "All notable changes to this project will be documented in this file.",
                  "",
                  "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),",
                  "and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).",
                  "",
                  "## [Unreleased]",
                  ""
              ]

              sections = [
                  ('security', 'Security'),
                  ('breaking', 'Breaking Changes'),
                  ('deprecated', 'Deprecated'),
                  ('added', 'Added'),
                  ('changed', 'Changed'),
                  ('fixed', 'Fixed'),
                  ('removed', 'Removed')
              ]

              # Show unreleased changes first
              for section_key, section_label in sections:
                  unreleased_commits = [c for c in categorized[section_key] if not c['tag']]
                  if unreleased_commits:
                      changelog_lines.append(f"### {section_label}")
                      for commit in unreleased_commits:
                          changelog_lines.append(format_commit_entry(commit))
                      changelog_lines.append("")

              # Show tagged releases
              for tag in tags:
                  changelog_lines.append(f"## [{tag['name']}] - {tag['date']}")
                  changelog_lines.append("")
                  
                  # Find commits for this tag
                  for section_key, section_label in sections:
                      tagged_commits = [c for c in categorized[section_key] if c['tag'] == tag['name']]
                      if tagged_commits:
                          changelog_lines.append(f"### {section_label}")
                          for commit in tagged_commits:
                              changelog_lines.append(format_commit_entry(commit))
                          changelog_lines.append("")

              return "\n".join(changelog_lines)

          try:
              content = generate_full_changelog()
              with open('CHANGELOG.md', 'w', encoding='utf-8') as f:
                  f.write(content)
              print("Successfully generated changelog.")
          except Exception as e:
              print(f"Error generating changelog: {e}")
              sys.exit(1)
          EOF

      - name: Commit Updated Changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: update changelog [skip ci]"
            git push
          fi
