name: Update Changelog
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Changelog from Commits
        run: |
          cat > CHANGELOG.md << 'EOL'
          # Changelog

          All notable changes to this project are documented in this file.

          The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).

          ## [Unreleased]

          EOL
          
          # Get filtered commits
          git log --pretty=format:"%s|||%b|||%an|||%ad" --date=short --grep="docs: update changelog" --grep="Update changelog.yml" --grep="Create changelog.yml" --grep="\[skip ci\]" --invert-grep > commits.tmp
          
          # Process Added section
          echo "### Added" >> CHANGELOG.md
          grep -i "add\|new\|create\|implement\|feat" commits.tmp | while IFS='|||' read -r subject body author date || [ -n "$subject" ]; do
            echo "- **$subject** ($date)" >> CHANGELOG.md
            if [ -n "$body" ] && [ "$body" != "" ]; then
              echo "$body" | sed 's/^/  /' >> CHANGELOG.md
            fi
          done
          echo "" >> CHANGELOG.md
          
          # Process Changed section
          echo "### Changed" >> CHANGELOG.md
          grep -i "update\|change\|improve\|refactor\|modify" commits.tmp | while IFS='|||' read -r subject body author date || [ -n "$subject" ]; do
            echo "- **$subject** ($date)" >> CHANGELOG.md
            if [ -n "$body" ] && [ "$body" != "" ]; then
              echo "$body" | sed 's/^/  /' >> CHANGELOG.md
            fi
          done
          echo "" >> CHANGELOG.md
          
          # Process Fixed section  
          echo "### Fixed" >> CHANGELOG.md
          grep -i "fix\|resolve\|correct\|patch\|bug" commits.tmp | while IFS='|||' read -r subject body author date || [ -n "$subject" ]; do
            echo "- **$subject** ($date)" >> CHANGELOG.md
            if [ -n "$body" ] && [ "$body" != "" ]; then
              echo "$body" | sed 's/^/  /' >> CHANGELOG.md
            fi
          done
          echo "" >> CHANGELOG.md
          
          # Cleanup
          rm commits.tmp
      - name: Commit Updated Changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: update changelog [skip ci]"
            git push
          fi
